support deployment to cloudfoundry
Adds a cloudfoundry manifest.yml

You can deploy this app with `cf push food-ratings-demo`.

Having a file called `gunicorn.py` in the root caused the deployment to
get confused, with the following error:

    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
    AttributeError: 'module' object has no attribute '__path__'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/vcap/app/.heroku/python/bin/gunicorn", line 7, in <module>
        from gunicorn.app.wsgiapp import run
    ImportError: No module named 'gunicorn.app'; 'gunicorn' is not a package

This is fixed by renaming `gunicorn.py` to something else (I chose
`run-gunicorn.py`).